import {
  Municipality,
  Neighborhood,
  Property,
  User,
  FieldCycle,
  Ovitrap,
  StrategicPoint,
  SpecialProperty,
  EpidemiologicalEvent,
  EpidemiologicalBlock,
  CitizenComplaint,
  SupplyItem,
  Equipment,
  PlanningTask,
  Alert,
  AuditLog,
  IntersectoralReferral,
} from '../types';

export const initialMunicipality: Municipality = {
  id: 'mun-santacruz-01',
  name: 'Santa Cruz do Sul',
  state: 'RS',
  ibgeCode: '4316808',
  coatOfArmsUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=120&auto=format&fit=crop&q=80',
  healthSecretaryName: 'Dr. Roberto Albuquerque',
  healthSecretaryPhone: '(51) 3715-1200',
  coordinatorName: 'Lucas Menezes (Biólogo)',
  coordinatorPhone: '(51) 3715-1244',
  address: 'Rua Marechal Floriano, 900 - Centro, Santa Cruz do Sul - RS',
  activeCycleId: 'cycle-2026-01',
  totalProperties: 10090,
  totalAgents: 42,
  totalSupervisors: 6,
  settings: {
    riskWeights: {
      recentFoci: 25,
      recurrence: 20,
      ovitraps: 15,
      pendingVisits: 15,
      closedProperties: 10,
      complaints: 5,
      strategicPoints: 5,
      epidemiologicalEvents: 5,
      lowCoverage: 10,
    },
    recurrenceThresholdDays: 90,
    recurrenceThresholdCount: 3,
  },
};

export const initialUsers: User[] = [
  {
    id: 'usr-admin-01',
    name: 'Carlos Drummond',
    email: 'superadmin@endemias.gov.br',
    cpf: '00123456789',
    registrationNumber: 'ADM-001',
    role: 'SUPER_ADMIN',
    municipalityId: 'mun-santacruz-01',
    active: true,
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'usr-admin-mun',
    name: 'Mariana Lopes',
    email: 'gestao@santacruz.rs.gov.br',
    cpf: '11122233344',
    registrationNumber: 'ADM-MUN-04',
    role: 'MUNICIPAL_ADMIN',
    municipalityId: 'mun-santacruz-01',
    active: true,
    createdAt: '2025-01-12T08:00:00Z',
  },
  {
    id: 'usr-sec-01',
    name: 'Dr. Roberto Albuquerque',
    email: 'secretario@saude.santacruz.rs.gov.br',
    cpf: '22233344455',
    registrationNumber: 'SMS-901',
    role: 'HEALTH_SECRETARY',
    municipalityId: 'mun-santacruz-01',
    active: true,
    createdAt: '2025-01-01T08:00:00Z',
  },
  {
    id: 'usr-coord-01',
    name: 'Lucas Menezes',
    email: 'coordenacao@endemias.santacruz.rs.gov.br',
    cpf: '33344455566',
    registrationNumber: 'END-012',
    role: 'ENDEMIAS_COORDINATOR',
    municipalityId: 'mun-santacruz-01',
    active: true,
    createdAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'usr-sup-01',
    name: 'Marcos Vinícius',
    email: 'supervisor.marcos@endemias.gov.br',
    cpf: '44455566677',
    registrationNumber: 'SUP-108',
    role: 'FIELD_SUPERVISOR',
    municipalityId: 'mun-santacruz-01',
    teamId: 'team-01',
    active: true,
    createdAt: '2025-02-01T08:00:00Z',
  },
  {
    id: 'usr-ace-01',
    name: 'João Silva',
    email: 'ace.joao@endemias.gov.br',
    cpf: '55566677788',
    registrationNumber: 'ACE-4821',
    role: 'ACE',
    municipalityId: 'mun-santacruz-01',
    teamId: 'team-01',
    phone: '(51) 99876-5432',
    active: true,
    createdAt: '2025-02-10T08:00:00Z',
  },
  {
    id: 'usr-ace-02',
    name: 'Maria Eduarda Soares',
    email: 'ace.maria@endemias.gov.br',
    cpf: '66677788899',
    registrationNumber: 'ACE-4822',
    role: 'ACE',
    municipalityId: 'mun-santacruz-01',
    teamId: 'team-01',
    phone: '(51) 99876-5433',
    active: true,
    createdAt: '2025-02-10T08:00:00Z',
  },
  {
    id: 'usr-epi-01',
    name: 'Dra. Camila Ramos',
    email: 'epidemiologia@saude.santacruz.rs.gov.br',
    cpf: '77788899900',
    registrationNumber: 'EPI-302',
    role: 'EPIDEMIOLOGY_AGENT',
    municipalityId: 'mun-santacruz-01',
    active: true,
    createdAt: '2025-01-20T08:00:00Z',
  },
  {
    id: 'usr-san-01',
    name: 'Fernando Costa',
    email: 'visa@santacruz.rs.gov.br',
    cpf: '88899900011',
    registrationNumber: 'SAN-514',
    role: 'SANITARY_AGENT',
    municipalityId: 'mun-santacruz-01',
    active: true,
    createdAt: '2025-01-22T08:00:00Z',
  },
  {
    id: 'usr-auditor-01',
    name: 'Beatriz Santos',
    email: 'auditoria@saude.gov.br',
    cpf: '99900011122',
    registrationNumber: 'AUD-880',
    role: 'AUDITOR_VIEWER',
    municipalityId: 'mun-santacruz-01',
    active: true,
    createdAt: '2025-01-25T08:00:00Z',
  },
];

export const initialCycle: FieldCycle = {
  id: 'cycle-2026-01',
  municipalityId: 'mun-santacruz-01',
  name: '1º Ciclo 2026 — LIRAa / LIA',
  year: 2026,
  number: 1,
  startDate: '2026-01-15',
  endDate: '2026-03-31',
  goalPercentage: 80.0,
  currentCoveragePercentage: 74.5,
  totalTargetProperties: 10090,
  visitedProperties: 7517,
  fociCount: 48,
  closedCount: 840,
  refusalCount: 65,
  status: 'EM_ANDAMENTO',
};

export const initialNeighborhoods: Neighborhood[] = [
  {
    id: 'bairro-vila-nova',
    municipalityId: 'mun-santacruz-01',
    zoneId: 'zona-norte',
    name: 'Vila Nova',
    estimatedPopulation: 14200,
    totalProperties: 1840,
    totalSectors: 8,
    totalBlocks: 64,
    responsibleAgents: ['João Silva', 'Maria Eduarda Soares'],
    coveragePercentage: 67.2,
    fociCount: 14,
    pendingVisitsCount: 112,
    riskScore: 82,
    riskLevel: 'CRITICO',
    latitude: -29.7125,
    longitude: -52.4290,
  },
  {
    id: 'bairro-centro',
    municipalityId: 'mun-santacruz-01',
    zoneId: 'zona-central',
    name: 'Centro',
    estimatedPopulation: 28500,
    totalProperties: 3420,
    totalSectors: 14,
    totalBlocks: 110,
    responsibleAgents: ['Carlos Eduardo', 'Aline Freitas'],
    coveragePercentage: 78.4,
    fociCount: 6,
    pendingVisitsCount: 145,
    riskScore: 38,
    riskLevel: 'ATENCAO',
    latitude: -29.7180,
    longitude: -52.4280,
  },
  {
    id: 'bairro-jd-america',
    municipalityId: 'mun-santacruz-01',
    zoneId: 'zona-sul',
    name: 'Jardim América',
    estimatedPopulation: 18900,
    totalProperties: 2150,
    totalSectors: 9,
    totalBlocks: 72,
    responsibleAgents: ['Pedro Henrique', 'Patrícia Lima'],
    coveragePercentage: 72.0,
    fociCount: 9,
    pendingVisitsCount: 98,
    riskScore: 61,
    riskLevel: 'ALTO',
    latitude: -29.7280,
    longitude: -52.4350,
  },
  {
    id: 'bairro-sao-cristovao',
    municipalityId: 'mun-santacruz-01',
    zoneId: 'zona-leste',
    name: 'São Cristóvão',
    estimatedPopulation: 11300,
    totalProperties: 1480,
    totalSectors: 6,
    totalBlocks: 48,
    responsibleAgents: ['Rodrigo Alves'],
    coveragePercentage: 84.1,
    fociCount: 2,
    pendingVisitsCount: 42,
    riskScore: 21,
    riskLevel: 'BAIXO',
    latitude: -29.7080,
    longitude: -52.4180,
  },
  {
    id: 'bairro-industrial',
    municipalityId: 'mun-santacruz-01',
    zoneId: 'zona-oeste',
    name: 'Distrito Industrial',
    estimatedPopulation: 4800,
    totalProperties: 680,
    totalSectors: 4,
    totalBlocks: 28,
    responsibleAgents: ['Marcos Vinícius (Supervisor)'],
    coveragePercentage: 89.5,
    fociCount: 12,
    pendingVisitsCount: 18,
    riskScore: 74,
    riskLevel: 'ALTO',
    latitude: -29.7340,
    longitude: -52.4490,
  },
  {
    id: 'bairro-rural-distrito',
    municipalityId: 'mun-santacruz-01',
    zoneId: 'zona-rural',
    name: 'Distrito Rural Monte Alverne',
    estimatedPopulation: 3200,
    totalProperties: 520,
    totalSectors: 3,
    totalBlocks: 18,
    responsibleAgents: ['Geraldo Silveira'],
    coveragePercentage: 79.2,
    fociCount: 5,
    pendingVisitsCount: 26,
    riskScore: 35,
    riskLevel: 'ATENCAO',
    latitude: -29.6700,
    longitude: -52.4700,
  },
];

export const initialProperties: Property[] = [
  {
    id: 'prop-001',
    municipalityId: 'mun-santacruz-01',
    code: 'IMV-000104',
    address: 'Rua São José',
    number: '342',
    complement: 'Casa',
    neighborhood: 'Vila Nova',
    neighborhoodId: 'bairro-vila-nova',
    sector: 'Setor 01',
    block: 'Quadra 14',
    latitude: -29.7120,
    longitude: -52.4285,
    zone: 'URBANA',
    type: 'RESIDENCIA',
    status: 'FOCO',
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    residentName: 'Dona Antônia Carvalho',
    residentPhone: '(51) 98122-3344',
    notes: 'Presença de tambor de 200L sem tampa com água de chuva e larvas ativas.',
    isRecurrent: true,
    fociHistoryCount: 4,
    lastVisitDate: '2026-03-02T10:30:00Z',
    lastVisitStatus: 'TRABALHADO',
    totalVisitsCount: 6,
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-03-02T10:30:00Z',
  },
  {
    id: 'prop-002',
    municipalityId: 'mun-santacruz-01',
    code: 'IMV-000105',
    address: 'Rua São José',
    number: '350',
    complement: 'Fundos',
    neighborhood: 'Vila Nova',
    neighborhoodId: 'bairro-vila-nova',
    sector: 'Setor 01',
    block: 'Quadra 14',
    latitude: -29.7123,
    longitude: -52.4288,
    zone: 'URBANA',
    type: 'RESIDENCIA',
    status: 'REINCIDENTE',
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    residentName: 'Claudio Roberto Nunes',
    residentPhone: '(51) 98765-4321',
    notes: 'Imóvel com histórico de 3 focos consecutivos em calhas entupidas e pratinhos.',
    isRecurrent: true,
    fociHistoryCount: 3,
    lastVisitDate: '2026-02-28T09:15:00Z',
    lastVisitStatus: 'TRABALHADO',
    totalVisitsCount: 5,
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-02-28T09:15:00Z',
  },
  {
    id: 'prop-003',
    municipalityId: 'mun-santacruz-01',
    code: 'IMV-000106',
    address: 'Rua São José',
    number: '368',
    complement: 'Lote Vago',
    neighborhood: 'Vila Nova',
    neighborhoodId: 'bairro-vila-nova',
    sector: 'Setor 01',
    block: 'Quadra 14',
    latitude: -29.7126,
    longitude: -52.4292,
    zone: 'URBANA',
    type: 'TERRENO_BALDIO',
    status: 'RISCO_CRITICO',
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    notes: 'Terreno com acúmulo de carcaças, garrafas descartadas e mato alto.',
    isRecurrent: false,
    fociHistoryCount: 2,
    lastVisitDate: '2026-03-01T14:20:00Z',
    lastVisitStatus: 'TRABALHADO',
    totalVisitsCount: 4,
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-03-01T14:20:00Z',
  },
  {
    id: 'prop-004',
    municipalityId: 'mun-santacruz-01',
    code: 'IMV-000107',
    address: 'Avenida Independência',
    number: '1240',
    neighborhood: 'Vila Nova',
    neighborhoodId: 'bairro-vila-nova',
    sector: 'Setor 02',
    block: 'Quadra 16',
    latitude: -29.7135,
    longitude: -52.4300,
    zone: 'URBANA',
    type: 'BORRACHARIA',
    status: 'PENDENTE',
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    residentName: 'Valdir Borracheiro',
    residentPhone: '(51) 99112-8877',
    notes: 'Ponto estratégico. Pneus cobertos parcialmente, inspeção quinzenal obrigatória.',
    isRecurrent: false,
    fociHistoryCount: 1,
    lastVisitDate: '2026-02-18T11:00:00Z',
    lastVisitStatus: 'TRABALHADO',
    totalVisitsCount: 8,
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-02-18T11:00:00Z',
  },
  {
    id: 'prop-005',
    municipalityId: 'mun-santacruz-01',
    code: 'IMV-000108',
    address: 'Rua Marechal Deodoro',
    number: '512',
    complement: 'Apto 101',
    neighborhood: 'Centro',
    neighborhoodId: 'bairro-centro',
    sector: 'Setor 03',
    block: 'Quadra 08',
    latitude: -29.7175,
    longitude: -52.4270,
    zone: 'URBANA',
    type: 'RESIDENCIA',
    status: 'NORMAL',
    responsibleAgentId: 'usr-ace-02',
    responsibleAgentName: 'Maria Eduarda Soares',
    residentName: 'Dra. Helena Vaz',
    residentPhone: '(51) 98844-5566',
    notes: 'Imóvel sem depósitos com água. Moradora colaborativa.',
    isRecurrent: false,
    fociHistoryCount: 0,
    lastVisitDate: '2026-03-03T09:00:00Z',
    lastVisitStatus: 'TRABALHADO',
    totalVisitsCount: 4,
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-03-03T09:00:00Z',
  },
  {
    id: 'prop-006',
    municipalityId: 'mun-santacruz-01',
    code: 'IMV-000109',
    address: 'Rua Marechal Deodoro',
    number: '528',
    neighborhood: 'Centro',
    neighborhoodId: 'bairro-centro',
    sector: 'Setor 03',
    block: 'Quadra 08',
    latitude: -29.7178,
    longitude: -52.4273,
    zone: 'URBANA',
    type: 'RESIDENCIA',
    status: 'FECHADO',
    responsibleAgentId: 'usr-ace-02',
    responsibleAgentName: 'Maria Eduarda Soares',
    notes: 'Morador ausente em horário comercial. Deixado panfleto e agendado retorno.',
    isRecurrent: false,
    fociHistoryCount: 0,
    lastVisitDate: '2026-03-03T09:20:00Z',
    lastVisitStatus: 'FECHADO',
    totalVisitsCount: 3,
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-03-03T09:20:00Z',
  },
  {
    id: 'prop-007',
    municipalityId: 'mun-santacruz-01',
    code: 'IMV-000110',
    address: 'Rua das Flores',
    number: '89',
    neighborhood: 'Jardim América',
    neighborhoodId: 'bairro-jd-america',
    sector: 'Setor 05',
    block: 'Quadra 22',
    latitude: -29.7285,
    longitude: -52.4345,
    zone: 'URBANA',
    type: 'RESIDENCIA',
    status: 'RECUSA',
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    notes: 'Proprietário recusou entrada do agente. Notificação enviada à supervisão.',
    isRecurrent: false,
    fociHistoryCount: 1,
    lastVisitDate: '2026-02-25T15:10:00Z',
    lastVisitStatus: 'RECUSA',
    totalVisitsCount: 3,
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-02-25T15:10:00Z',
  },
  {
    id: 'prop-008',
    municipalityId: 'mun-santacruz-01',
    code: 'IMV-000111',
    address: 'Rodovia RS-409, Km 4',
    number: 'S/N',
    neighborhood: 'Distrito Industrial',
    neighborhoodId: 'bairro-industrial',
    sector: 'Setor 08',
    block: 'Quadra 02',
    latitude: -29.7345,
    longitude: -52.4500,
    zone: 'URBANA',
    type: 'DEPOSITO',
    status: 'FOCO',
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    residentName: 'Sucatas & Metais Sul Ltda',
    residentPhone: '(51) 3719-9000',
    notes: 'Ferro-velho com caçambas a céu aberto. Encontrado foco em peças automotivas.',
    isRecurrent: true,
    fociHistoryCount: 5,
    lastVisitDate: '2026-03-01T16:00:00Z',
    lastVisitStatus: 'TRABALHADO',
    totalVisitsCount: 10,
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-03-01T16:00:00Z',
  }
];

export const initialOvitraps: Ovitrap[] = [
  {
    id: 'ovi-001',
    code: 'OVI-042',
    qrCode: 'OVITRAP-4316808-042',
    municipalityId: 'mun-santacruz-01',
    neighborhood: 'Vila Nova',
    sector: 'Setor 01',
    address: 'Rua São José, fundos UBS Vila Nova',
    latitude: -29.7118,
    longitude: -52.4282,
    installationDate: '2026-01-20',
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    status: 'COLETA_PENDENTE',
    lastCollectionDate: '2026-02-27',
    lastEggCount: 148,
    isPositive: true,
    consecutiveGrowth: true,
    growthAlert: true,
    history: [
      {
        date: '2026-02-13',
        eggCount: 42,
        isPositive: true,
        collectedBy: 'João Silva',
      },
      {
        date: '2026-02-20',
        eggCount: 95,
        isPositive: true,
        collectedBy: 'João Silva',
      },
      {
        date: '2026-02-27',
        eggCount: 148,
        isPositive: true,
        collectedBy: 'João Silva',
        observations: 'Aumento expressivo consecutivo de ovos de Aedes aegypti.',
      },
    ],
  },
  {
    id: 'ovi-002',
    code: 'OVI-043',
    qrCode: 'OVITRAP-4316808-043',
    municipalityId: 'mun-santacruz-01',
    neighborhood: 'Vila Nova',
    sector: 'Setor 02',
    address: 'Av. Independência, 1100 (Praça Central)',
    latitude: -29.7130,
    longitude: -52.4310,
    installationDate: '2026-01-20',
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    status: 'ATIVA',
    lastCollectionDate: '2026-03-02',
    lastEggCount: 112,
    isPositive: true,
    consecutiveGrowth: true,
    growthAlert: true,
    history: [
      {
        date: '2026-02-16',
        eggCount: 30,
        isPositive: true,
        collectedBy: 'João Silva',
      },
      {
        date: '2026-02-23',
        eggCount: 68,
        isPositive: true,
        collectedBy: 'João Silva',
      },
      {
        date: '2026-03-02',
        eggCount: 112,
        isPositive: true,
        collectedBy: 'João Silva',
      },
    ],
  },
  {
    id: 'ovi-003',
    code: 'OVI-015',
    qrCode: 'OVITRAP-4316808-015',
    municipalityId: 'mun-santacruz-01',
    neighborhood: 'Centro',
    sector: 'Setor 03',
    address: 'Parque da Gruta, entrada oeste',
    latitude: -29.7190,
    longitude: -52.4265,
    installationDate: '2026-01-18',
    responsibleAgentId: 'usr-ace-02',
    responsibleAgentName: 'Maria Eduarda Soares',
    status: 'ATIVA',
    lastCollectionDate: '2026-03-01',
    lastEggCount: 14,
    isPositive: true,
    consecutiveGrowth: false,
    growthAlert: false,
    history: [
      {
        date: '2026-02-15',
        eggCount: 18,
        isPositive: true,
        collectedBy: 'Maria Eduarda Soares',
      },
      {
        date: '2026-02-22',
        eggCount: 22,
        isPositive: true,
        collectedBy: 'Maria Eduarda Soares',
      },
      {
        date: '2026-03-01',
        eggCount: 14,
        isPositive: true,
        collectedBy: 'Maria Eduarda Soares',
      },
    ],
  },
  {
    id: 'ovi-004',
    code: 'OVI-022',
    qrCode: 'OVITRAP-4316808-022',
    municipalityId: 'mun-santacruz-01',
    neighborhood: 'São Cristóvão',
    sector: 'Setor 06',
    address: 'Rua Ernesto Alves, 820',
    latitude: -29.7085,
    longitude: -52.4175,
    installationDate: '2026-01-20',
    responsibleAgentId: 'usr-ace-02',
    responsibleAgentName: 'Maria Eduarda Soares',
    status: 'ATIVA',
    lastCollectionDate: '2026-03-03',
    lastEggCount: 0,
    isPositive: false,
    consecutiveGrowth: false,
    growthAlert: false,
    history: [
      {
        date: '2026-02-17',
        eggCount: 0,
        isPositive: false,
        collectedBy: 'Maria Eduarda Soares',
      },
      {
        date: '2026-02-24',
        eggCount: 2,
        isPositive: true,
        collectedBy: 'Maria Eduarda Soares',
      },
      {
        date: '2026-03-03',
        eggCount: 0,
        isPositive: false,
        collectedBy: 'Maria Eduarda Soares',
      },
    ],
  },
];

export const initialStrategicPoints: StrategicPoint[] = [
  {
    id: 'pe-001',
    municipalityId: 'mun-santacruz-01',
    name: 'Borracharia & Recapadora Central',
    type: 'BORRACHARIA',
    contactName: 'Antônio Marcos',
    contactPhone: '(51) 99877-1122',
    address: 'Av. Independência, 1420',
    neighborhood: 'Vila Nova',
    latitude: -29.7140,
    longitude: -52.4315,
    inspectionFrequencyDays: 15,
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    riskLevel: 'CRITICO',
    lastInspectionDate: '2026-02-15',
    nextInspectionDate: '2026-03-02', // Vencida
    isInspectionOverdue: true,
    totalInspections: 14,
    fociHistoryCount: 6,
  },
  {
    id: 'pe-002',
    municipalityId: 'mun-santacruz-01',
    name: 'Ferro Velho Rodoviário & Sucatas',
    type: 'FERRO_VELHO',
    contactName: 'Luciano Ferraz',
    contactPhone: '(51) 99123-4567',
    address: 'BR-471, Km 125',
    neighborhood: 'Distrito Industrial',
    latitude: -29.7350,
    longitude: -52.4510,
    inspectionFrequencyDays: 15,
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    riskLevel: 'CRITICO',
    lastInspectionDate: '2026-02-14',
    nextInspectionDate: '2026-03-01', // Vencida
    isInspectionOverdue: true,
    totalInspections: 12,
    fociHistoryCount: 5,
  },
  {
    id: 'pe-003',
    municipalityId: 'mun-santacruz-01',
    name: 'Cemitério Municipal da Paz',
    type: 'CEMITERIO',
    contactName: 'Administração Municipal',
    contactPhone: '(51) 3715-9988',
    address: 'Rua São Lourenço, 300',
    neighborhood: 'Centro',
    latitude: -29.7210,
    longitude: -52.4240,
    inspectionFrequencyDays: 15,
    responsibleAgentId: 'usr-ace-02',
    responsibleAgentName: 'Maria Eduarda Soares',
    riskLevel: 'ALTO',
    lastInspectionDate: '2026-02-26',
    nextInspectionDate: '2026-03-13',
    isInspectionOverdue: false,
    totalInspections: 18,
    fociHistoryCount: 3,
  },
  {
    id: 'pe-004',
    municipalityId: 'mun-santacruz-01',
    name: 'EcoRecicla Cooperativa de Catadores',
    type: 'RECICLADORA',
    contactName: 'Sra. Marisa Santos',
    contactPhone: '(51) 98744-1234',
    address: 'Rua Rui Barbosa, 890',
    neighborhood: 'Jardim América',
    latitude: -29.7290,
    longitude: -52.4370,
    inspectionFrequencyDays: 15,
    responsibleAgentId: 'usr-ace-01',
    responsibleAgentName: 'João Silva',
    riskLevel: 'ALTO',
    lastInspectionDate: '2026-02-28',
    nextInspectionDate: '2026-03-15',
    isInspectionOverdue: false,
    totalInspections: 10,
    fociHistoryCount: 2,
  },
];

export const initialSpecialProperties: SpecialProperty[] = [
  {
    id: 'ie-001',
    municipalityId: 'mun-santacruz-01',
    name: 'Escola Municipal de Ensino Fundamental Monteiro Lobato',
    type: 'ESCOLA',
    address: 'Rua São José, 780',
    neighborhood: 'Vila Nova',
    responsiblePerson: 'Profª. Clarice Lispector',
    contactPhone: '(51) 3715-4421',
    latitude: -29.7110,
    longitude: -52.4270,
    lastInspectionDate: '2026-02-22',
    fociCount: 0,
  },
  {
    id: 'ie-002',
    municipalityId: 'mun-santacruz-01',
    name: 'Hospital Regional do Vale',
    type: 'HOSPITAL_UBS',
    address: 'Rua Marechal Floriano, 1500',
    neighborhood: 'Centro',
    responsiblePerson: 'Dr. Geraldo Alckmin Jr.',
    contactPhone: '(51) 3715-6000',
    latitude: -29.7160,
    longitude: -52.4250,
    lastInspectionDate: '2026-02-27',
    fociCount: 0,
  },
  {
    id: 'ie-003',
    municipalityId: 'mun-santacruz-01',
    name: 'Estação Rodoviária Intermunicipal',
    type: 'TERMINAL_RODOVIARIO',
    address: 'Av. Deputado Euclydes Kliemann, 100',
    neighborhood: 'Centro',
    responsiblePerson: 'Carlos Eduardo Ramos',
    contactPhone: '(51) 3715-3344',
    latitude: -29.7220,
    longitude: -52.4300,
    lastInspectionDate: '2026-02-25',
    fociCount: 1,
  },
];

export const initialEpidemiologicalEvents: EpidemiologicalEvent[] = [
  {
    id: 'epi-001',
    municipalityId: 'mun-santacruz-01',
    disease: 'DENGUE',
    notificationDate: '2026-03-01',
    neighborhood: 'Vila Nova',
    sector: 'Setor 01',
    latitude: -29.7122,
    longitude: -52.4287,
    priority: 'CRITICA',
    status: 'BLOQUEIO_EM_EXECUCAO',
    associatedBlockId: 'blq-001',
  },
  {
    id: 'epi-002',
    municipalityId: 'mun-santacruz-01',
    disease: 'DENGUE',
    notificationDate: '2026-03-02',
    neighborhood: 'Vila Nova',
    sector: 'Setor 01',
    latitude: -29.7128,
    longitude: -52.4295,
    priority: 'URGENTE',
    status: 'BLOQUEIO_EM_EXECUCAO',
    associatedBlockId: 'blq-001',
  },
  {
    id: 'epi-003',
    municipalityId: 'mun-santacruz-01',
    disease: 'CHIKUNGUNYA',
    notificationDate: '2026-03-03',
    neighborhood: 'Jardim América',
    sector: 'Setor 05',
    latitude: -29.7288,
    longitude: -52.4355,
    priority: 'URGENTE',
    status: 'BLOQUEIO_PLANEJADO',
  },
];

export const initialEpidemiologicalBlocks: EpidemiologicalBlock[] = [
  {
    id: 'blq-001',
    code: 'BLQ-2026-014',
    municipalityId: 'mun-santacruz-01',
    eventId: 'epi-001',
    disease: 'DENGUE (Sorotipo 2)',
    targetNeighborhood: 'Vila Nova',
    targetSector: 'Setor 01 - Quadras 14, 15, 16',
    radiusMeters: 150,
    scheduledDate: '2026-03-04',
    assignedTeamId: 'team-01',
    assignedTeamName: 'Equipe Norte 01',
    priority: 'URGENTE',
    status: 'EM_ANDAMENTO',
    propertiesForecast: 100,
    propertiesVisited: 78,
    propertiesClosed: 12,
    propertiesPending: 10,
    fociFound: 4,
    coveragePercentage: 78.0,
  },
  {
    id: 'blq-002',
    code: 'BLQ-2026-015',
    municipalityId: 'mun-santacruz-01',
    eventId: 'epi-003',
    disease: 'CHIKUNGUNYA',
    targetNeighborhood: 'Jardim América',
    targetSector: 'Setor 05 - Quadras 21, 22',
    radiusMeters: 150,
    scheduledDate: '2026-03-05',
    assignedTeamId: 'team-02',
    assignedTeamName: 'Equipe Sul 02',
    priority: 'ALTA',
    status: 'PLANEJADO',
    propertiesForecast: 80,
    propertiesVisited: 41,
    propertiesClosed: 9,
    propertiesPending: 30,
    fociFound: 2,
    coveragePercentage: 51.2,
  },
];

export const initialComplaints: CitizenComplaint[] = [
  {
    id: 'comp-001',
    protocol: 'END-2026-000235',
    municipalityId: 'mun-santacruz-01',
    type: 'TERRENO_BALDIO',
    description: 'Terreno abandonado com descarte irregular de pneus e garrafas plásticas acumulando água das chuvas recentes.',
    address: 'Rua São José, próximo ao nº 360',
    neighborhood: 'Vila Nova',
    latitude: -29.7125,
    longitude: -52.4291,
    citizenName: 'Maria Antônia Fernandes',
    citizenPhone: '(51) 98223-1199',
    status: 'ATRIBUIDA',
    assignedAgentId: 'usr-ace-01',
    assignedAgentName: 'João Silva',
    createdAt: '2026-03-01T11:42:00Z',
  },
  {
    id: 'comp-002',
    protocol: 'END-2026-000236',
    municipalityId: 'mun-santacruz-01',
    type: 'PISCINA_ABANDONADA',
    description: 'Piscina sem tratamento químico com água verde e larvas visíveis na superfície em residência desocupada.',
    address: 'Rua Marechal Deodoro, 640',
    neighborhood: 'Centro',
    latitude: -29.7185,
    longitude: -52.4280,
    citizenName: 'Anônimo (Cidadão)',
    status: 'VISTORIA_REALIZADA',
    assignedAgentId: 'usr-ace-02',
    assignedAgentName: 'Maria Eduarda Soares',
    createdAt: '2026-02-28T14:10:00Z',
    resolutionNotes: 'Realizada vistoria. Aplicado larvicida biológico BTI (50ml) e notificado o proprietário.',
    resolutionFociFound: true,
  },
  {
    id: 'comp-003',
    protocol: 'END-2026-000237',
    municipalityId: 'mun-santacruz-01',
    type: 'AGUA_PARADA',
    description: 'Caçamba de entulho na via pública acumulando água de chuva há mais de 10 dias.',
    address: 'Rua das Flores, 112',
    neighborhood: 'Jardim América',
    latitude: -29.7282,
    longitude: -52.4340,
    citizenName: 'Paulo Siqueira',
    citizenPhone: '(51) 99334-5566',
    status: 'TRIAGEM',
    createdAt: '2026-03-03T08:15:00Z',
  },
  {
    id: 'comp-004',
    protocol: 'END-2026-000238',
    municipalityId: 'mun-santacruz-01',
    type: 'PNEUS',
    description: 'Acúmulo de cerca de 40 pneus nos fundos de oficina mecânica sem cobertura.',
    address: 'Av. Independência, 1500',
    neighborhood: 'Vila Nova',
    latitude: -29.7145,
    longitude: -52.4320,
    citizenName: 'Renato Lima',
    status: 'RECEBIDA',
    createdAt: '2026-03-03T10:40:00Z',
  },
];

export const initialSupplies: SupplyItem[] = [
  {
    id: 'sup-001',
    municipalityId: 'mun-santacruz-01',
    name: 'Pyriproxyfen 0.5% Granulado (Larvicida IGR)',
    category: 'LARVICIDA',
    unit: 'KG',
    currentStock: 185.5,
    minimumStock: 50.0,
    isLowStock: false,
    batches: [
      {
        batchNumber: 'PYR-2025-08',
        expirationDate: '2027-08-30',
        quantity: 120.0,
        supplier: 'Ministério da Saúde / DLOG',
        isNearExpiration: false,
      },
      {
        batchNumber: 'PYR-2024-11',
        expirationDate: '2026-05-15',
        quantity: 65.5,
        supplier: 'Ministério da Saúde / DLOG',
        isNearExpiration: true,
      },
    ],
  },
  {
    id: 'sup-002',
    municipalityId: 'mun-santacruz-01',
    name: 'Bacillus thuringiensis israelensis (BTI Líquido)',
    category: 'LARVICIDA',
    unit: 'LITROS',
    currentStock: 34.0,
    minimumStock: 40.0,
    isLowStock: true,
    batches: [
      {
        batchNumber: 'BTI-2025-02',
        expirationDate: '2026-11-20',
        quantity: 34.0,
        supplier: 'Laboratório Bioquímica Brasil',
        isNearExpiration: false,
      },
    ],
  },
  {
    id: 'sup-003',
    municipalityId: 'mun-santacruz-01',
    name: 'Máscara PFF2 com Válvula de Exalação',
    category: 'EPI',
    unit: 'UNIDADE',
    currentStock: 480,
    minimumStock: 150,
    isLowStock: false,
    batches: [
      {
        batchNumber: 'EPI-PFF2-2025',
        expirationDate: '2028-12-31',
        quantity: 480,
        supplier: 'Delta Equipamentos de Segurança',
        isNearExpiration: false,
      },
    ],
  },
  {
    id: 'sup-004',
    municipalityId: 'mun-santacruz-01',
    name: 'Luvas Nitrílicas de Cano Longo (Par)',
    category: 'EPI',
    unit: 'UNIDADE',
    currentStock: 320,
    minimumStock: 100,
    isLowStock: false,
    batches: [
      {
        batchNumber: 'LUV-NIT-2025',
        expirationDate: '2029-01-01',
        quantity: 320,
        supplier: 'Delta Equipamentos de Segurança',
        isNearExpiration: false,
      },
    ],
  },
  {
    id: 'sup-005',
    municipalityId: 'mun-santacruz-01',
    name: 'Palhetas de Eucatex para Ovitrampas (Pacote c/ 50)',
    category: 'MATERIAL_OVITRAMPA',
    unit: 'PACOTE',
    currentStock: 18,
    minimumStock: 25,
    isLowStock: true,
    batches: [
      {
        batchNumber: 'PAL-2025-A',
        expirationDate: '2030-01-01',
        quantity: 18,
        supplier: 'Marcenaria & Suprimentos Biológicos',
        isNearExpiration: false,
      },
    ],
  },
];

export const initialEquipments: Equipment[] = [
  {
    id: 'eq-001',
    municipalityId: 'mun-santacruz-01',
    patrimonyNumber: 'PAT-00982',
    name: 'Termonebulizador UBV Costal Guarany',
    type: 'TERMONEBULIZADOR',
    serialNumber: 'GRN-4492-2024',
    status: 'EM_USO',
    assignedToUser: 'João Silva',
    lastMaintenanceDate: '2026-01-10',
    nextPreventiveMaintenanceDate: '2026-03-10',
    isMaintenanceOverdue: false,
  },
  {
    id: 'eq-002',
    municipalityId: 'mun-santacruz-01',
    patrimonyNumber: 'PAT-00983',
    name: 'Termonebulizador UBV Costal Guarany',
    type: 'TERMONEBULIZADOR',
    serialNumber: 'GRN-4493-2024',
    status: 'MANUTENCAO',
    lastMaintenanceDate: '2025-11-20',
    nextPreventiveMaintenanceDate: '2026-02-20',
    isMaintenanceOverdue: true,
  },
  {
    id: 'eq-003',
    municipalityId: 'mun-santacruz-01',
    patrimonyNumber: 'PAT-01204',
    name: 'Tablet Samsung Galaxy Tab A9 64GB',
    type: 'TABLET',
    serialNumber: 'SM-X110-8992',
    status: 'EM_USO',
    assignedToUser: 'João Silva',
    lastMaintenanceDate: '2025-12-05',
    nextPreventiveMaintenanceDate: '2026-06-05',
    isMaintenanceOverdue: false,
  },
  {
    id: 'eq-004',
    municipalityId: 'mun-santacruz-01',
    patrimonyNumber: 'PAT-01205',
    name: 'Tablet Samsung Galaxy Tab A9 64GB',
    type: 'TABLET',
    serialNumber: 'SM-X110-8993',
    status: 'EM_USO',
    assignedToUser: 'Maria Eduarda Soares',
    lastMaintenanceDate: '2025-12-05',
    nextPreventiveMaintenanceDate: '2026-06-05',
    isMaintenanceOverdue: false,
  },
  {
    id: 'eq-005',
    municipalityId: 'mun-santacruz-01',
    patrimonyNumber: 'PAT-00310',
    name: 'Veículo Fiat Strada Endurance 1.4 (Vigilância)',
    type: 'VEICULO',
    serialNumber: 'PLACA-JBG-9A12',
    status: 'EM_USO',
    assignedToUser: 'Marcos Vinícius (Supervisor)',
    lastMaintenanceDate: '2026-02-01',
    nextPreventiveMaintenanceDate: '2026-05-01',
    isMaintenanceOverdue: false,
  },
];

export const initialTasks: PlanningTask[] = [
  {
    id: 'tsk-001',
    municipalityId: 'mun-santacruz-01',
    date: '2026-03-04',
    type: 'BLOQUEIO_QUIMICO',
    priority: 'URGENTE',
    neighborhood: 'Vila Nova',
    sector: 'Setor 01',
    block: 'Quadra 14',
    propertyCode: 'IMV-000104',
    assignedAgentId: 'usr-ace-01',
    assignedAgentName: 'João Silva',
    supervisorId: 'usr-sup-01',
    supervisorName: 'Marcos Vinícius',
    status: 'EM_ANDAMENTO',
    notes: 'Realizar bloqueio peridomiciliar num raio de 150m do caso notificado de Dengue.',
  },
  {
    id: 'tsk-002',
    municipalityId: 'mun-santacruz-01',
    date: '2026-03-04',
    type: 'PONTO_ESTRATEGICO',
    priority: 'ALTA',
    neighborhood: 'Vila Nova',
    sector: 'Setor 01',
    assignedAgentId: 'usr-ace-01',
    assignedAgentName: 'João Silva',
    supervisorId: 'usr-sup-01',
    supervisorName: 'Marcos Vinícius',
    status: 'PENDENTE',
    notes: 'Vistoriar Borracharia Central (PE-001) com inspeção quinzenal vencida.',
  },
  {
    id: 'tsk-003',
    municipalityId: 'mun-santacruz-01',
    date: '2026-03-04',
    type: 'DENUNCIA',
    priority: 'ALTA',
    neighborhood: 'Vila Nova',
    sector: 'Setor 01',
    propertyCode: 'IMV-000106',
    assignedAgentId: 'usr-ace-01',
    assignedAgentName: 'João Silva',
    supervisorId: 'usr-sup-01',
    supervisorName: 'Marcos Vinícius',
    status: 'PENDENTE',
    notes: 'Verificar denúncia protocolo END-2026-000235 sobre terreno baldio com pneus.',
  },
  {
    id: 'tsk-004',
    municipalityId: 'mun-santacruz-01',
    date: '2026-03-04',
    type: 'OVITRAMPA',
    priority: 'ATENCAO',
    neighborhood: 'Vila Nova',
    sector: 'Setor 01',
    assignedAgentId: 'usr-ace-01',
    assignedAgentName: 'João Silva',
    supervisorId: 'usr-sup-01',
    supervisorName: 'Marcos Vinícius',
    status: 'PENDENTE',
    notes: 'Fazer coleta semanal da palheta OVI-042 e instalar nova palheta identificada.',
  },
  {
    id: 'tsk-005',
    municipalityId: 'mun-santacruz-01',
    date: '2026-03-04',
    type: 'VISITA_DE_ROTINA',
    priority: 'NORMAL',
    neighborhood: 'Centro',
    sector: 'Setor 03',
    assignedAgentId: 'usr-ace-02',
    assignedAgentName: 'Maria Eduarda Soares',
    supervisorId: 'usr-sup-01',
    supervisorName: 'Marcos Vinícius',
    status: 'EM_ANDAMENTO',
    notes: 'Dar continuidade às visitas domiciliares de rotina do 1º Ciclo nas Quadras 08 e 09.',
  },
];

export const initialAlerts: Alert[] = [
  {
    id: 'alt-001',
    municipalityId: 'mun-santacruz-01',
    category: 'EPIDEMIOLOGICO',
    level: 'CRITICO',
    title: 'Alerta Crítico: Setor Norte (Vila Nova) com Risco 82/100',
    description: 'Bairro Vila Nova apresenta 14 focos recentes, 2 ovitrampas com crescimento consecutivo e 2 notificações clínicas de Dengue.',
    neighborhood: 'Vila Nova',
    sector: 'Setor 01',
    assignedTo: 'Lucas Menezes (Coordenador)',
    resolved: false,
    createdAt: '2026-03-03T07:30:00Z',
  },
  {
    id: 'alt-002',
    municipalityId: 'mun-santacruz-01',
    category: 'ENTOMOLOGICO',
    level: 'IMPORTANTE',
    title: 'Ovitrampa OVI-042 com crescimento exponencial',
    description: 'Contagem subiu consecutivamente de 42 para 95 e 148 ovos na última leitura quinzenal.',
    neighborhood: 'Vila Nova',
    assignedTo: 'João Silva',
    resolved: false,
    createdAt: '2026-03-02T16:00:00Z',
  },
  {
    id: 'alt-003',
    municipalityId: 'mun-santacruz-01',
    category: 'OPERACIONAL',
    level: 'ATENCAO',
    title: '2 Pontos Estratégicos com inspeção quinzenal vencida',
    description: 'Borracharia & Recapadora Central (PE-001) e Ferro Velho Rodoviário (PE-002) ultrapassaram 15 dias sem inspeção.',
    neighborhood: 'Vila Nova / Industrial',
    assignedTo: 'Marcos Vinícius (Supervisor)',
    resolved: false,
    createdAt: '2026-03-03T08:00:00Z',
  },
  {
    id: 'alt-004',
    municipalityId: 'mun-santacruz-01',
    category: 'ADMINISTRATIVO',
    level: 'ATENCAO',
    title: 'Estoque de BTI Líquido abaixo da margem mínima',
    description: 'Saldo atual de 34 Litros está inferior ao estoque mínimo recomendado de 40 Litros para o ciclo.',
    assignedTo: 'Mariana Lopes',
    resolved: false,
    createdAt: '2026-03-02T11:20:00Z',
  },
];

export const initialReferrals: IntersectoralReferral[] = [
  {
    id: 'ref-001',
    protocol: 'ENC-2026-0089',
    municipalityId: 'mun-santacruz-01',
    targetSector: 'LIMPEZA_URBANA',
    propertyAddress: 'Rua São José, Lote 14 (frente ao nº 368)',
    neighborhood: 'Vila Nova',
    latitude: -29.7126,
    longitude: -52.4292,
    description: 'Solicitação urgente de capina e retirada de entulhos/carcaças em terreno baldio com acúmulo crônico de água pluvial e larvas.',
    issuedByAgentName: 'João Silva (ACE)',
    status: 'EM_ANDAMENTO',
    createdAt: '2026-03-01T15:30:00Z',
  },
  {
    id: 'ref-002',
    protocol: 'ENC-2026-0090',
    municipalityId: 'mun-santacruz-01',
    targetSector: 'VIGILANCIA_SANITARIA',
    propertyAddress: 'Av. Independência, 1420 (Borracharia)',
    neighborhood: 'Vila Nova',
    latitude: -29.7140,
    longitude: -52.4315,
    description: 'Notificação para fiscalização de armazenamento inadequado de pneus expostos ao ar livre sem cobertura em estabelecimento comercial.',
    issuedByAgentName: 'Marcos Vinícius (Supervisor)',
    status: 'RECEBIDO',
    createdAt: '2026-03-02T09:45:00Z',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-001',
    municipalityId: 'mun-santacruz-01',
    userId: 'usr-coord-01',
    userName: 'Lucas Menezes',
    userRole: 'ENDEMIAS_COORDINATOR',
    operation: 'LOGIN',
    timestamp: '2026-03-04T07:15:20Z',
    ipAddress: '177.135.44.12',
    device: 'Desktop Chrome 122 (Linux/GCP)',
    module: 'Autenticação',
    recordIdentifier: 'Sessão iniciada com sucesso',
  },
  {
    id: 'log-002',
    municipalityId: 'mun-santacruz-01',
    userId: 'usr-ace-01',
    userName: 'João Silva',
    userRole: 'ACE',
    operation: 'CADASTRO',
    timestamp: '2026-03-03T16:45:10Z',
    ipAddress: '189.28.12.80',
    device: 'Samsung Galaxy Tab A9 (Mobile PWA)',
    module: 'Visitas Domiciliares',
    recordIdentifier: 'VIS-2026-8941 (IMV-000104)',
    newValue: 'Visita trabalhada. Foco detectado em tambor A2. Larvicida Pyriproxyfen aplicado (2g).',
  },
  {
    id: 'log-003',
    municipalityId: 'mun-santacruz-01',
    userId: 'usr-sup-01',
    userName: 'Marcos Vinícius',
    userRole: 'FIELD_SUPERVISOR',
    operation: 'APROVACAO',
    timestamp: '2026-03-03T17:10:00Z',
    ipAddress: '177.135.44.12',
    device: 'Desktop Firefox 123 (Windows)',
    module: 'Planejamento de Campo',
    recordIdentifier: 'Aprovação Rota Inteligente de Amanhã (ACE João Silva)',
  },
];
